# -*- coding: utf-8 -*-
"""DLIP_Lab4_youhyeonPark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6g0do8_txipyIyXbhuseIabTXRqPw71
"""

import os
from google.colab import drive
drive.mount('/content/drive')
root_path = '/content/drive/MyDrive/DLIP/Lab4'  #change dir to your project folder
os.chdir(root_path)  #change dir
os.getcwd()

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DLIP/Lab4

with open('groundtruth.txt', 'r') as file:
    ground_truth= file.readlines()

with open('counting_result.txt', 'r') as file:
    detected = file.readlines()

# 데이터 정리
ground_truth = [int(value.strip().split(',')[1]) for value in ground_truth]
detected = [int(value.strip().split()[1]) for value in detected]

# 공통된 데이터 샘플만 사용
min_samples = min(len(ground_truth), len(detected))
ground_truth = ground_truth[:min_samples]
detected = detected[:min_samples]

# Accuracy 계산
accuracy = np.mean(np.array(ground_truth) == np.array(detected))

# 결과 출력
print("Accuracy:", accuracy)